apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment_name_var
  labels:
    app: app_name_var
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app_name_var
  template:
    metadata:
      labels:
        app: app_name_var
    spec:
      containers:
      - name: app_name_var
        image: nexus_registry_url/Nexus_repository_name:Nexus_tag
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
      serviceAccount: service_account_name_var
