apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding_name_var
  namespace: namespace_var
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role_name_var
subjects:
- kind: ServiceAccount
  name: service_account_name_var
  namespace: calculator
